// Mock admin data service for demo
export const getMockAlerts = () => [
  {
    id: 1,
    title: 'Earthquake Alert - 6.5 Magnitude',
    description: 'A 6.5 magnitude earthquake detected 15km from coast',
    severity: 'high',
    source: 'USGS',
    verified: true,
    longitude: -122.4194,
    latitude: 37.7749,
    createdAt: new Date(),
    reports: 45,
  },
  {
    id: 2,
    title: 'Flash Flood Warning',
    description: 'Heavy rainfall causing flash flooding in downtown areas',
    severity: 'high',
    source: 'NOAA',
    verified: true,
    longitude: -118.2437,
    latitude: 34.0522,
    createdAt: new Date(Date.now() - 3600000),
    reports: 32,
  },
  {
    id: 3,
    title: 'Wildfire Watch - High Fire Danger',
    description: 'Red flag warning in effect - high fire danger conditions',
    severity: 'medium',
    source: 'Cal Fire',
    verified: true,
    longitude: -122.0842,
    latitude: 37.4220,
    createdAt: new Date(Date.now() - 7200000),
    reports: 28,
  },
  {
    id: 4,
    title: 'Severe Thunderstorm Warning',
    description: 'Large hail and damaging winds moving through the area',
    severity: 'medium',
    source: 'National Weather Service',
    verified: true,
    longitude: -87.6298,
    latitude: 41.8781,
    createdAt: new Date(Date.now() - 10800000),
    reports: 15,
  },
  {
    id: 5,
    title: 'Air Quality Alert',
    description: 'Poor air quality from nearby wildfires',
    severity: 'low',
    source: 'EPA',
    verified: true,
    longitude: -122.3321,
    latitude: 47.6062,
    createdAt: new Date(Date.now() - 14400000),
    reports: 8,
  },
];

export const getStats = () => ({
  totalDisasters: 5,
  highPriority: 2,
  mediumPriority: 2,
  lowPriority: 1,
  withPhotos: 3,
  needingHelp: 128,
});
